import { useState, useRef } from "react";
import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  Download, 
  FileText, 
  AlertCircle,
  CheckCircle2,
  TestTube,
  Bug
} from "lucide-react";
import { toast } from "sonner";
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const PDFTest = () => {
  const [testResults, setTestResults] = useState<string[]>([]);
  const testElementRef = useRef<HTMLDivElement>(null);

  const addTestResult = (result: string) => {
    setTestResults(prev => [...prev, `${new Date().toLocaleTimeString()}: ${result}`]);
  };

  const testSimplePDF = async () => {
    try {
      addTestResult("Starting simple PDF test...");
      
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      pdf.setFontSize(20);
      pdf.text('PDF Test Document', 105, 30, { align: 'center' });
      
      pdf.setFontSize(14);
      pdf.text('This is a test PDF generated by jsPDF', 20, 50);
      pdf.text('If you can see this, jsPDF is working correctly.', 20, 70);
      pdf.text(`Generated at: ${new Date().toLocaleString()}`, 20, 90);
      
      const fileName = `pdf-test-${Date.now()}.pdf`;
      pdf.save(fileName);
      
      addTestResult("✅ Simple PDF test successful");
      toast.success('Simple PDF downloaded successfully!');
    } catch (error) {
      addTestResult(`❌ Simple PDF test failed: ${error.message}`);
      toast.error('Simple PDF test failed');
      console.error('Simple PDF error:', error);
    }
  };

  const testHTML2Canvas = async () => {
    try {
      addTestResult("Starting html2canvas test...");
      
      if (!testElementRef.current) {
        throw new Error('Test element not found');
      }

      const canvas = await html2canvas(testElementRef.current, {
        scale: 1,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        logging: true
      });

      addTestResult(`✅ html2canvas successful - Canvas size: ${canvas.width}x${canvas.height}`);
      
      // Test image download
      const link = document.createElement('a');
      link.download = `html2canvas-test-${Date.now()}.png`;
      link.href = canvas.toDataURL();
      link.click();
      
      addTestResult("✅ Image download successful");
      toast.success('html2canvas test successful!');
    } catch (error) {
      addTestResult(`❌ html2canvas test failed: ${error.message}`);
      toast.error('html2canvas test failed');
      console.error('html2canvas error:', error);
    }
  };

  const testCombinedPDF = async () => {
    try {
      addTestResult("Starting combined PDF test...");
      
      if (!testElementRef.current) {
        throw new Error('Test element not found');
      }

      // Step 1: Create canvas
      addTestResult("Creating canvas...");
      const canvas = await html2canvas(testElementRef.current, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        logging: false
      });

      addTestResult(`Canvas created: ${canvas.width}x${canvas.height}`);

      // Step 2: Create PDF
      addTestResult("Creating PDF...");
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const imgData = canvas.toDataURL('image/png', 1.0);
      addTestResult("Image data created");

      // Calculate dimensions
      const pdfWidth = 210; // A4 width in mm
      const pdfHeight = 297; // A4 height in mm
      const imgAspectRatio = canvas.width / canvas.height;
      const pdfAspectRatio = pdfWidth / pdfHeight;
      
      let finalWidth, finalHeight, xOffset, yOffset;
      
      if (imgAspectRatio > pdfAspectRatio) {
        finalWidth = pdfWidth;
        finalHeight = pdfWidth / imgAspectRatio;
        xOffset = 0;
        yOffset = (pdfHeight - finalHeight) / 2;
      } else {
        finalHeight = pdfHeight;
        finalWidth = pdfHeight * imgAspectRatio;
        xOffset = (pdfWidth - finalWidth) / 2;
        yOffset = 0;
      }

      addTestResult(`PDF dimensions: ${finalWidth}x${finalHeight} at offset (${xOffset}, ${yOffset})`);

      pdf.addImage(imgData, 'PNG', xOffset, yOffset, finalWidth, finalHeight);
      
      const fileName = `combined-test-${Date.now()}.pdf`;
      pdf.save(fileName);
      
      addTestResult("✅ Combined PDF test successful");
      toast.success('Combined PDF test successful!');
    } catch (error) {
      addTestResult(`❌ Combined PDF test failed: ${error.message}`);
      toast.error('Combined PDF test failed');
      console.error('Combined PDF error:', error);
    }
  };

  const clearResults = () => {
    setTestResults([]);
  };

  const testBrowserSupport = () => {
    const results = [];
    
    // Test jsPDF
    try {
      const testPdf = new jsPDF();
      results.push("✅ jsPDF library loaded");
    } catch (error) {
      results.push("❌ jsPDF library error");
    }

    // Test html2canvas
    try {
      if (typeof html2canvas === 'function') {
        results.push("✅ html2canvas library loaded");
      } else {
        results.push("❌ html2canvas not available");
      }
    } catch (error) {
      results.push("❌ html2canvas library error");
    }

    // Test Canvas support
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (ctx) {
        results.push("✅ Canvas API supported");
      } else {
        results.push("❌ Canvas API not supported");
      }
    } catch (error) {
      results.push("❌ Canvas API error");
    }

    // Test Blob support
    try {
      const blob = new Blob(['test'], { type: 'text/plain' });
      results.push("✅ Blob API supported");
    } catch (error) {
      results.push("❌ Blob API not supported");
    }

    // Test URL.createObjectURL
    try {
      const blob = new Blob(['test'], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      URL.revokeObjectURL(url);
      results.push("✅ URL.createObjectURL supported");
    } catch (error) {
      results.push("❌ URL.createObjectURL not supported");
    }

    setTestResults(results);
    addTestResult("Browser support test completed");
  };

  return (
    <Layout>
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-4">
          <h1 className="text-3xl font-bold flex items-center justify-center gap-2">
            <TestTube className="h-8 w-8 text-primary" />
            PDF Download Debug Center
          </h1>
          <p className="text-muted-foreground">
            Test and debug PDF generation functionality
          </p>
        </div>

        {/* Test Element */}
        <Card>
          <CardHeader>
            <CardTitle>Test Certificate Element</CardTitle>
            <CardDescription>
              This element will be used for html2canvas testing
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div 
              ref={testElementRef}
              className="p-8 bg-gradient-to-br from-primary/5 to-accent/5 rounded-lg border-2 border-dashed border-primary/20"
            >
              <div className="text-center space-y-4">
                <h2 className="text-2xl font-bold text-primary">Test Certificate</h2>
                <p className="text-lg">This certifies that</p>
                <p className="text-3xl font-bold">John Doe</p>
                <p className="text-lg">has completed the PDF test</p>
                <div className="flex justify-center gap-4 mt-6">
                  <Badge variant="secondary">Skills: 10</Badge>
                  <Badge variant="secondary">Hours: 50</Badge>
                  <Badge variant="secondary">Score: 95%</Badge>
                </div>
                <p className="text-sm text-muted-foreground mt-4">
                  Generated on {new Date().toLocaleDateString()}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Test Controls */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Bug className="h-5 w-5" />
              Test Controls
            </CardTitle>
            <CardDescription>
              Run different tests to identify PDF download issues
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              <Button onClick={testBrowserSupport} variant="outline" className="gap-2">
                <CheckCircle2 className="h-4 w-4" />
                Test Browser Support
              </Button>
              
              <Button onClick={testSimplePDF} className="gap-2">
                <FileText className="h-4 w-4" />
                Test Simple PDF
              </Button>
              
              <Button onClick={testHTML2Canvas} variant="outline" className="gap-2">
                <Download className="h-4 w-4" />
                Test html2canvas
              </Button>
              
              <Button onClick={testCombinedPDF} className="gap-2">
                <Download className="h-4 w-4" />
                Test Combined PDF
              </Button>
            </div>
            
            <div className="flex justify-center">
              <Button onClick={clearResults} variant="ghost" size="sm">
                Clear Results
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Test Results */}
        <Card>
          <CardHeader>
            <CardTitle>Test Results</CardTitle>
            <CardDescription>
              Debug information and test outcomes
            </CardDescription>
          </CardHeader>
          <CardContent>
            {testResults.length === 0 ? (
              <Alert>
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>
                  No test results yet. Run a test to see debug information.
                </AlertDescription>
              </Alert>
            ) : (
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {testResults.map((result, index) => (
                  <div 
                    key={index} 
                    className={`p-2 rounded text-sm font-mono ${
                      result.includes('✅') ? 'bg-green-50 text-green-800' :
                      result.includes('❌') ? 'bg-red-50 text-red-800' :
                      'bg-gray-50 text-gray-800'
                    }`}
                  >
                    {result}
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Instructions */}
        <Card>
          <CardHeader>
            <CardTitle>Debugging Instructions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <h4 className="font-medium">Step 1: Test Browser Support</h4>
              <p className="text-sm text-muted-foreground">
                Check if all required APIs are available in your browser.
              </p>
            </div>
            
            <div className="space-y-2">
              <h4 className="font-medium">Step 2: Test Simple PDF</h4>
              <p className="text-sm text-muted-foreground">
                Test basic jsPDF functionality without html2canvas.
              </p>
            </div>
            
            <div className="space-y-2">
              <h4 className="font-medium">Step 3: Test html2canvas</h4>
              <p className="text-sm text-muted-foreground">
                Test if html2canvas can capture the test element.
              </p>
            </div>
            
            <div className="space-y-2">
              <h4 className="font-medium">Step 4: Test Combined PDF</h4>
              <p className="text-sm text-muted-foreground">
                Test the full pipeline: html2canvas → jsPDF → download.
              </p>
            </div>
            
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                If any test fails, check the browser console for detailed error messages.
                Common issues include browser security restrictions, missing libraries, or CORS problems.
              </AlertDescription>
            </Alert>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
};